baseURL = 'https://sk4r-git.github.io'
title = "TEST CONFIG"
languageCode = "fr-fr"
theme = "risotto"

[taxonomies]
category = ""
tag = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true